### ISSUE TITLE
مشکل تاریخ یکم هرماه ۱۴۰۴

### ISSUE THREAD

**Issue by abbasalim** [hamooo90/jalali-datepicker-compose#1]
سلام کتابخونه تون عالیه منتها ، یکم ماه های ۱۴۰۴ که انتخاب میکنید ۲ م ثبت میشه. ممنون میشیم رفعش کنید

**Comment by hamooo90** [comment]
سلام. طبق بررسی که کردم به این مشکل بر نخوردم. مشکل فقط در سال 1404 اتفاق می افته؟ ساعت و تاریخ دستگاهی که تست میکنید بررسی کنید و با نمونه کدی که در readme هست امتحان کنید.
