### ISSUE TITLE
تغییر فونت

### ISSUE THREAD

**Issue by momeni1367** [hamooo90/jalali-datepicker-compose#2]
سلام تقویم فارسی خیلی خوبیه
میشه تغییرفونت هم بهش اضافه کنید

**Comment by momeni1367** [comment]
کی مینوتید تغییرفونت بهش اضافه کنید؟؟

**Comment by hamooo90** [comment]
سلام. ممنون از پیشنهادتون. سعی میکنم تا اواخر هفته آینده این قابلیت رو اضافه کنم. ولی هیچ قولی نمیدم.

**Comment by momeni1367** [comment]
تغییر فونت عالی دم شما گرم
