### ISSUE TITLE
استایل دلخواه بریا متن ها

### ISSUE THREAD

**Issue by ihoseinam** [hamooo90/jalali-datepicker-compose#4]
سلام
امکان ست کردن تکست استایل دلخواه برای دکمه ها و اعداد هم قرار بدید

**Comment by hamooo90** [comment]
سلام.
امکان تغییر فونت و رنگ تکست و اعداد وجود دارد.
چه استایل های دیگه مورد نظرتون هست؟

**Comment by ihoseinam** [comment]
سلام
استایل تکست ها
اگه اشتباه نکنم از یه بادی لارج به طور پیش فرض  استفاده می‌کنه،
من بادی لارج رو زیادی بزرگ تنظیم کردم تو پروژه و خراب میشه،
این امکان بشه که استایل کل تکست هارو بتونی عوض کنی عالی میشه
ممنون

**Comment by hamooo90** [comment]
برای تغییر استایل باید تغییرات زیادی در سورس کد بدم و متاسفانه فرصت این کار رو ندارم.
ولی کتابخانه رو آپدیت کردم و امکان تغییر سایز فونت رو اضافه کردم.
نسخه کتابخانه را بروز کنید و از پارامتر fontSize برای اندازه تکست اسفاده کنید. 
امیدوارم مشکلتون حل شده باشه.

**Comment by ihoseinam** [comment]
تشکر❤️
