### ISSUE TITLE
تاریخ میلادی

### ISSUE THREAD

**Issue by ainoapp** [hamooo90/jalali-datepicker-compose#6]
سلام وقت بخیر
ما برای یک اپلیکیشن ازکتابخانه تون استفاده میکنیم که هم تاریخ میلادی و هم تاریخ شمسی رو ساپورت میکنه
امکانش هست تاریخ میلادی هم اضافه کنید؟ وقتی که تقویم رو صدا میزنیم با یک پارامتر تعیین کنیم میلادی باشه یا شمسی.

**Comment by hamooo90** [comment]
سلام.
متاسفانه در حال حاضر فرصت افزودن این قابلیت به کتابخانه رو ندارم. شاید در آینده اضافه کنم.
